[package]
name = "curriculum-test"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
dotenv = "0.15.0"
sqlx = { version = "0.7.4", features = ["mysql", "runtime-async-std"] }
